### ISSUE TITLE
Escritorio

### ISSUE THREAD

**Issue by PMJimena123** [Programa-TrainIT-Ar/PAT#24]

**Comment by PMJimena123** [comment]
Funcionalidad de:

Escritorio
![Image](https://github.com/user-attachments/assets/c2dc6e8f-e85f-49db-8fbe-bba7253a61bb)

**Comment by ThamairyGonzalez** [comment]
@alexisbarroso12  Trabaja en este issues habia 2 creadas y asignadas a vos, no tenemos el permiso de eliminar o archivar asi qye le desvincule la milestone  y la desasigne deje solo esta como activa!! cualquier duda con @PMJimena123

**Comment by ThamairyGonzalez** [comment]
Cierro esta Tarea quedo 1 sola en TO DO ya asignada a Alexis  @PMJimena123
